# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('visibility', models.BooleanField()),
            ],
        ),
    ]
